# visualisation params
VIEW_WIDTH = 900
VIEW_HEIGHT = 800
VIEW_SCALE = 2
ARM_THICKNESS = 3
SHEET_COLOR = (50, 50, 50)
CONTOUR_THICKNESS = 1
CONTOUR_COLOR = (90, 90, 90)

# sheet positioning
SHEET_WIDTH = 297
SHEET_HEIGHT = 210
SHEET_DISTANCE = 90

# arm physical params
UPPER_ARM_LENGTH = 170
FOREARM_LENGTH = 220
MIN_DISTANCE = 80

# movement
TRAVEL_SPEED = 10  # mm / sec
DRAW_SPEED = 5  # mm / sec
Z_SPEED = 0.5  # drop / sec
HOME_X = SHEET_WIDTH / 2
HOME_Y = SHEET_HEIGHT / 2
Z_UP = 1
Z_DOWN = 0
